---
title: "SDS 192 Group Contract"
author:
 - Caitlyn Kim
 - Annabelle Daniels
 - Lily Schroeder
date: "Last updated on `r Sys.Date()`"
output: html_document
---

Working in groups can be both incredibly rewarding and incredibly challenging. The most effective collaborations explicitly outline group roles, expectations, and procedures in advance to coordinate how the group will operate, to establish mechanisms of accountability, and to mitigate the risk of conflict. It is important that, throughout the semester, you address group concerns as they come up. This may involve assigning someone to check in with team members that are falling behind, establishing expectations for attending office hours and asking for help, calling team meetings to discuss issues, or reaching out to the instructor to resolve enduring and unresolved conflicts.		

# ROLES

## Who will be responsible for scheduling meetings and hosting Zoom calls? 

Lily

## Who will be responsible for facilitating discussion during team meetings?

Together

## Who will be responsible for taking notes and recording decisions during meetings?

Annabelle

## Who will be responsible for emailing the professor with questions?

Caitlyn

## Who will be responsible for requesting group assignment extensions?

Annabelle

## Who will be responsible for setting deadlines for drafts? 

Lily

## Who will be responsible for checking in with team members when drafts are late?

Caitlyn

## Who will be responsible for reviewing all materials before submission?

All of us

## Who will be responsible for submitting assignments?

Lily but at a meeting


# COLLABORATIVE WORKSPACES

## Where will the team keep meeting notes? 

Google Doc

## Where will the team store drafts of assignments? 

GitHub

## Through what channels will the team communicate when not meeting?

Through text

## What is the expected response time for emails and messages? 

Within a day


# MEETINGS

## How often will the team meet? 

Weekly at least

## What days/times will the team meet?

Thursdays at 5

## How long will meetings be?

One hour or as long as needed

## How will you make decisions during meetings (e.g. consensus, a vote)?

Consensus
		
## What strategies will you use to stay on task during meetings?

Keeping each other focused

## How should team members inform each other if they are going to be late to a meeting?

Through message
			
## When is it ok for a team member to skip a meeting? How soon should they inform the group?

At least in advance and only if there's not reschedule possible

## What will you do if a group member is chronically absent from or late to meetings?

Get in contact with them

## What will you do if a group member is consistently not participating in meetings?

Check in with them, see if they need help

## What are your expectations for respectful engagement and communication during meetings and in collaborative workspaces? What will you do if a member of your team does not meet these expectations?

Being kind and respectful. Have honest conversations if people aren't meeting those standards.


# ASSIGNMENTS

## How will you ensure that all team members fully understand assignment expectations? What will you do if your team is unsure how to complete an assignment?

Go through assignment together, go to office hours if we all don't know.

## How will you ensure that all team members are contributing equitably to assignments?

Break up the work before starting

## How soon in advance of deadlines do you expect all team members to share drafts of their work?

At least two days in advance

## What will be your process for reviewing each other’s work before submission?

Look over at team meetings

## What will you do if the quality of a team member’s work does not meet the group’s expectations? When is it permissible to revise another team member’s work?

Ask respectfully if you can suggest changes to their work.

## What are your expectations around punctuality regarding group deadlines? How should team members inform each other if they need an extension?

Let the team know at least a few days before, but otherwise extensions are ok.

## What will you do if a student is consistently late in submitting draft work?

Ask if they need help.

## What will you do if you discover that a team member’s work violates the Academic Code of Conduct?

Notify Lindsay.

# SIGNATURES

* I participated in drafting the standards, roles, and procedures outlined in this document.
* I agree to abide by the terms and conditions outlined in this document.			
* I understand that failing to abide by the terms and conditions outlined in this document may impact my grade.
 							
Signature: Lily Schroeder 
Date: `r format(Sys.time(), '%d %B, %Y')`

Signature: Caitlyn Kim 
Date: `r format(Sys.time(), '%d %B, %Y')`

Signature: Annabelle Daniels
Date `r format(Sys.time(), '%d %B, %Y')`


Once you are done, in the Git tab in your Environment pane, stage and commit your changes, and then push them to your GitHub repo.  

